spring:
  application:
    name: say-port
  cloud:
    config:
      import-check:
        enabled: false

##Run Application -> -Dserver.port=? para lanzar instancias con diferente puerto
server:
  port: 8091
  
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
